// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9qpGwrTQ3hPYa1w_ile-yglf8JYfcVI',
    appId: '1:828767293611:web:a394bdd734d6650cfa67ee',
    messagingSenderId: '828767293611',
    projectId: 'tokio-marine-80d9d',
    authDomain: 'tokio-marine-80d9d.firebaseapp.com',
    storageBucket: 'tokio-marine-80d9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCV_nlOkoHL69GE3T8Zejlq87lBG-BeL8',
    appId: '1:828767293611:android:2434ff87d2eabfaffa67ee',
    messagingSenderId: '828767293611',
    projectId: 'tokio-marine-80d9d',
    storageBucket: 'tokio-marine-80d9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfKcAnd1Vo8k16B8TEFX1ekBa7nyWQsSg',
    appId: '1:828767293611:ios:6136ab0e0fbaa376fa67ee',
    messagingSenderId: '828767293611',
    projectId: 'tokio-marine-80d9d',
    storageBucket: 'tokio-marine-80d9d.appspot.com',
    iosClientId: '828767293611-shjh3lq8gema93rjmuphfklu4orl9nro.apps.googleusercontent.com',
    iosBundleId: 'com.example.tokioMarine',
  );
}
